apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: phpmyadmin:nd
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php
  ports:
  - port: 5000
    name: admin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102